In [1]:
import pandas as pd
import numpy as np
accounts = pd.read_csv(r"D:\saas360\ravenstack_accounts.csv")
subscriptions = pd.read_csv(r"D:\saas360\ravenstack_subscriptions.csv")
feature_usage = pd.read_csv(r"D:\saas360\ravenstack_feature_usage.csv")
support_tickets = pd.read_csv(r"D:saas360\ravenstack_support_tickets.csv")
churn_events = pd.read_csv(r"D:saas360\ravenstack_churn_events.csv")

In [2]:
accounts_clean = accounts.copy()
subscriptions_clean = subscriptions.copy()
feature_usage_clean = feature_usage.copy()
support_tickets_clean = support_tickets.copy()
churn_events_clean = churn_events.copy()

In [3]:
def clean_column_names(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df

In [4]:
accounts_clean = clean_column_names(accounts_clean)
subscriptions_clean = clean_column_names(subscriptions_clean)
feature_usage_clean = clean_column_names(feature_usage_clean)
support_tickets_clean = clean_column_names(support_tickets_clean)
churn_events_clean = clean_column_names(churn_events_clean)

In [5]:
accounts_clean.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag'],
      dtype='object')

In [7]:
text_columns = [
    "account_name",
    "industry",
    "country",
    "referral_source",
    "plan_tier"
]

for col in text_columns:
    accounts_clean[col] = accounts_clean[col].str.strip()

In [8]:
subscriptions_clean["plan_tier"] = (
    subscriptions_clean["plan_tier"].str.strip()
)

subscriptions_clean["billing_frequency"] = (
    subscriptions_clean["billing_frequency"].str.strip()
)

feature_usage_clean["feature_name"] = (
    feature_usage_clean["feature_name"].str.strip()
)

support_tickets_clean["priority"] = (
    support_tickets_clean["priority"].str.strip()
)

churn_events_clean["reason_code"] = (
    churn_events_clean["reason_code"].str.strip()
)

In [9]:
accounts_clean["signup_date"] = pd.to_datetime(
    accounts_clean["signup_date"],
    errors="coerce"
)
subscriptions_clean["start_date"] = pd.to_datetime(
    subscriptions_clean["start_date"],
    errors="coerce"
)

subscriptions_clean["end_date"] = pd.to_datetime(
    subscriptions_clean["end_date"],
    errors="coerce"
)
feature_usage_clean["usage_date"] = pd.to_datetime(
    feature_usage_clean["usage_date"],
    errors="coerce"
)
support_tickets_clean["submitted_at"] = pd.to_datetime(
    support_tickets_clean["submitted_at"],
    errors="coerce"
)

support_tickets_clean["closed_at"] = pd.to_datetime(
    support_tickets_clean["closed_at"],
    errors="coerce"
)
churn_events_clean["churn_date"] = pd.to_datetime(
    churn_events_clean["churn_date"],
    errors="coerce"
)

In [10]:
subscriptions_clean[
    ["seats", "mrr_amount", "arr_amount"]
].dtypes

seats         int64
mrr_amount    int64
arr_amount    int64
dtype: object

In [11]:
subscriptions_clean["seats"] = pd.to_numeric(
    subscriptions_clean["seats"],
    errors="coerce"
)

subscriptions_clean["mrr_amount"] = pd.to_numeric(
    subscriptions_clean["mrr_amount"],
    errors="coerce"
)

subscriptions_clean["arr_amount"] = pd.to_numeric(
    subscriptions_clean["arr_amount"],
    errors="coerce"
)

feature_usage_clean["usage_count"] = pd.to_numeric(
    feature_usage_clean["usage_count"],
    errors="coerce"
)

feature_usage_clean["usage_duration_secs"] = pd.to_numeric(
    feature_usage_clean["usage_duration_secs"],
    errors="coerce"
)

feature_usage_clean["error_count"] = pd.to_numeric(
    feature_usage_clean["error_count"],
    errors="coerce"
)

In [12]:
duplicate_usage_ids = feature_usage_clean[
    feature_usage_clean["usage_id"].duplicated(keep=False)
].sort_values("usage_id")

duplicate_usage_ids

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
19294,U-0c9318,S-01b2dc,2023-12-11,feature_9,5,1060,3,False
17533,U-0c9318,S-0ffab0,2024-01-30,feature_11,3,1614,0,False
20588,U-13ce5b,S-9b623b,2023-03-26,feature_28,10,2050,1,False
9626,U-13ce5b,S-8b0950,2024-09-10,feature_9,8,824,0,True
18480,U-2103bb,S-7fc49b,2023-04-18,feature_12,9,5022,1,False
10379,U-2103bb,S-ae3270,2024-01-06,feature_3,10,5510,0,False
22,U-25b56c,S-810c27,2024-10-06,feature_20,7,231,0,False
7574,U-25b56c,S-34253c,2023-10-28,feature_20,6,2166,1,False
21376,U-48a4aa,S-93f835,2024-08-24,feature_39,10,4770,0,False
1085,U-48a4aa,S-383ac2,2023-02-12,feature_28,14,7126,0,False
20379,U-4ef9da,S-535e55,2024-06-10,feature_33,14,1358,0,False
15053,U-4ef9da,S-d0eeb2,2024-06-21,feature_5,14,1820,0,False
8965,U-52f4ae,S-444f22,2024-10-05,feature_6,9,3348,2,False
23870,U-52f4ae,S-0756ce,2024-03-30,feature_6,6,2178,1,False
23677,U-5cd3c2,S-fd790e,2024-11-30,feature_21,8,1216,0,False
11360,U-5cd3c2,S-dc90ef,2024-07-30,feature_5,11,6138,3,True
8482,U-649cec,S-2971ae,2023-07-07,feature_36,5,1165,0,False
21476,U-649cec,S-d54349,2024-12-25,feature_33,12,3456,2,False
20817,U-662254,S-f65381,2023-05-22,feature_11,9,1557,0,False
520,U-662254,S-3c072b,2023-10-24,feature_21,8,120,0,True
1967,U-6970d1,S-3f0fb6,2023-12-15,feature_25,4,1168,0,False
23519,U-6970d1,S-e43d0d,2024-04-03,feature_7,10,3630,0,False
23665,U-74b23f,S-51b3ed,2023-10-17,feature_33,9,4824,1,False
5680,U-74b23f,S-da9362,2024-03-23,feature_22,6,2118,0,False
22826,U-7a87ed,S-f1aa04,2023-07-10,feature_13,9,333,0,False
1213,U-7a87ed,S-3803ff,2024-04-05,feature_2,14,5516,0,False
22499,U-7c6703,S-124207,2023-11-30,feature_32,7,483,0,False
14716,U-7c6703,S-ae9ce7,2024-12-21,feature_40,13,897,0,False
768,U-8128da,S-6c969d,2024-05-27,feature_34,9,2520,0,False
4167,U-8128da,S-9c85b0,2023-04-21,feature_24,13,806,1,False
16271,U-8a3738,S-75c438,2023-05-13,feature_38,11,3608,0,False
20097,U-8a3738,S-472fda,2024-02-20,feature_19,12,4752,1,False
4335,U-ae1a6c,S-55db9e,2024-12-24,feature_17,12,420,2,False
15144,U-ae1a6c,S-d6aefa,2024-07-04,feature_26,13,4680,0,False
19989,U-b0ae95,S-21f8b3,2023-10-15,feature_5,12,5568,0,False
24004,U-b0ae95,S-1082f7,2024-06-09,feature_36,4,1440,0,False
13078,U-c878da,S-e133a5,2024-02-16,feature_29,10,2490,3,False
623,U-c878da,S-34f2f9,2024-03-27,feature_38,15,7170,0,False
17499,U-d20c6d,S-041624,2024-09-21,feature_2,17,323,0,False
4100,U-d20c6d,S-db56d2,2023-08-14,feature_14,8,1184,0,False
644,U-f42b0a,S-02ec76,2023-05-05,feature_8,7,4158,0,False
17127,U-f42b0a,S-17c51e,2023-06-24,feature_10,10,2510,0,True

In [15]:
duplicate_usage_ids.groupby("usage_id").size()

usage_id
U-0c9318    2
U-13ce5b    2
U-2103bb    2
U-25b56c    2
U-48a4aa    2
U-4ef9da    2
U-52f4ae    2
U-5cd3c2    2
U-649cec    2
U-662254    2
U-6970d1    2
U-74b23f    2
U-7a87ed    2
U-7c6703    2
U-8128da    2
U-8a3738    2
U-ae1a6c    2
U-b0ae95    2
U-c878da    2
U-d20c6d    2
U-f42b0a    2
dtype: int64

In [16]:
duplicate_usage_ids

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
19294,U-0c9318,S-01b2dc,2023-12-11,feature_9,5,1060,3,False
17533,U-0c9318,S-0ffab0,2024-01-30,feature_11,3,1614,0,False
20588,U-13ce5b,S-9b623b,2023-03-26,feature_28,10,2050,1,False
9626,U-13ce5b,S-8b0950,2024-09-10,feature_9,8,824,0,True
18480,U-2103bb,S-7fc49b,2023-04-18,feature_12,9,5022,1,False
10379,U-2103bb,S-ae3270,2024-01-06,feature_3,10,5510,0,False
22,U-25b56c,S-810c27,2024-10-06,feature_20,7,231,0,False
7574,U-25b56c,S-34253c,2023-10-28,feature_20,6,2166,1,False
21376,U-48a4aa,S-93f835,2024-08-24,feature_39,10,4770,0,False
1085,U-48a4aa,S-383ac2,2023-02-12,feature_28,14,7126,0,False
20379,U-4ef9da,S-535e55,2024-06-10,feature_33,14,1358,0,False
15053,U-4ef9da,S-d0eeb2,2024-06-21,feature_5,14,1820,0,False
8965,U-52f4ae,S-444f22,2024-10-05,feature_6,9,3348,2,False
23870,U-52f4ae,S-0756ce,2024-03-30,feature_6,6,2178,1,False
23677,U-5cd3c2,S-fd790e,2024-11-30,feature_21,8,1216,0,False
11360,U-5cd3c2,S-dc90ef,2024-07-30,feature_5,11,6138,3,True
8482,U-649cec,S-2971ae,2023-07-07,feature_36,5,1165,0,False
21476,U-649cec,S-d54349,2024-12-25,feature_33,12,3456,2,False
20817,U-662254,S-f65381,2023-05-22,feature_11,9,1557,0,False
520,U-662254,S-3c072b,2023-10-24,feature_21,8,120,0,True
1967,U-6970d1,S-3f0fb6,2023-12-15,feature_25,4,1168,0,False
23519,U-6970d1,S-e43d0d,2024-04-03,feature_7,10,3630,0,False
23665,U-74b23f,S-51b3ed,2023-10-17,feature_33,9,4824,1,False
5680,U-74b23f,S-da9362,2024-03-23,feature_22,6,2118,0,False
22826,U-7a87ed,S-f1aa04,2023-07-10,feature_13,9,333,0,False
1213,U-7a87ed,S-3803ff,2024-04-05,feature_2,14,5516,0,False
22499,U-7c6703,S-124207,2023-11-30,feature_32,7,483,0,False
14716,U-7c6703,S-ae9ce7,2024-12-21,feature_40,13,897,0,False
768,U-8128da,S-6c969d,2024-05-27,feature_34,9,2520,0,False
4167,U-8128da,S-9c85b0,2023-04-21,feature_24,13,806,1,False
16271,U-8a3738,S-75c438,2023-05-13,feature_38,11,3608,0,False
20097,U-8a3738,S-472fda,2024-02-20,feature_19,12,4752,1,False
4335,U-ae1a6c,S-55db9e,2024-12-24,feature_17,12,420,2,False
15144,U-ae1a6c,S-d6aefa,2024-07-04,feature_26,13,4680,0,False
19989,U-b0ae95,S-21f8b3,2023-10-15,feature_5,12,5568,0,False
24004,U-b0ae95,S-1082f7,2024-06-09,feature_36,4,1440,0,False
13078,U-c878da,S-e133a5,2024-02-16,feature_29,10,2490,3,False
623,U-c878da,S-34f2f9,2024-03-27,feature_38,15,7170,0,False
17499,U-d20c6d,S-041624,2024-09-21,feature_2,17,323,0,False
4100,U-d20c6d,S-db56d2,2023-08-14,feature_14,8,1184,0,False
644,U-f42b0a,S-02ec76,2023-05-05,feature_8,7,4158,0,False
17127,U-f42b0a,S-17c51e,2023-06-24,feature_10,10,2510,0,True

In [17]:
feature_usage_clean = feature_usage_clean.drop_duplicates()

In [18]:
feature_usage_clean["usage_event_key"] = (
    feature_usage_clean["usage_id"].astype(str)
    + "_"
    + feature_usage_clean.groupby("usage_id").cumcount().astype(str)
)

In [19]:
subscriptions_clean["end_date"].isna().sum()

4514

In [20]:
subscriptions_clean["subscription_status"] = np.where(
    subscriptions_clean["end_date"].isna(),
    "Active",
    "Ended"
)

In [21]:
support_tickets_clean["survey_responded"] = (
    support_tickets_clean["satisfaction_score"].notna()
)

In [22]:
churn_events_clean["feedback_text"]

0      switched to competitor
1                         NaN
2            missing features
3      switched to competitor
4               too expensive
                ...
595    switched to competitor
596                       NaN
597             too expensive
598                       NaN
599                       NaN
Name: feedback_text, Length: 600, dtype: object

In [23]:
usage_check = feature_usage_clean.merge(
    subscriptions_clean[
        ["subscription_id", "start_date", "end_date"]
    ],
    on="subscription_id",
    how="left"
)

In [24]:
usage_check["usage_timing_status"] = np.select(
    [
        usage_check["usage_date"] < usage_check["start_date"],
        
        usage_check["end_date"].notna() &
        (usage_check["usage_date"] > usage_check["end_date"])
    ],
    [
        "Before subscription",
        "After subscription"
    ],
    default="Within subscription"
)

In [25]:
usage_check["usage_timing_status"].value_counts()

usage_timing_status
Before subscription    19142
Within subscription     5568
After subscription       290
Name: count, dtype: int64

In [26]:
feature_usage_valid = usage_check[
    (
        usage_check["usage_date"] >=
        usage_check["start_date"]
    )
    &
    (
        usage_check["end_date"].isna()
        |
        (usage_check["usage_date"] <= usage_check["end_date"])
    )
].copy()

In [27]:
revenue_check = subscriptions_clean[
    ~np.isclose(
        subscriptions_clean["arr_amount"],
        subscriptions_clean["mrr_amount"] * 12
    )
]

print("Revenue mismatches:", len(revenue_check))

Revenue mismatches: 0

In [28]:
print(
    "Duplicate account IDs:",
    accounts_clean["account_id"].duplicated().sum()
)

print(
    "Duplicate subscription IDs:",
    subscriptions_clean["subscription_id"].duplicated().sum()
)

print(
    "Duplicate ticket IDs:",
    support_tickets_clean["ticket_id"].duplicated().sum()
)

print(
    "Duplicate churn IDs:",
    churn_events_clean["churn_event_id"].duplicated().sum()
)

Duplicate account IDs: 0
Duplicate subscription IDs: 0
Duplicate ticket IDs: 0
Duplicate churn IDs: 0

In [30]:
import os

os.makedirs(r"D:\saas360\cleaned", exist_ok=True)

print("Cleaned data folder is ready.")

Cleaned data folder is ready.

In [31]:
accounts_clean.to_csv(
    r"D:\saas360\cleaned\accounts_clean.csv",
    index=False
)

subscriptions_clean.to_csv(
    r"D:\saas360\cleaned\subscriptions_clean.csv",
    index=False
)

feature_usage_clean.to_csv(
    r"D:\saas360\cleaned\feature_usage_clean.csv",
    index=False
)

support_tickets_clean.to_csv(
    r"D:\saas360\cleaned\support_tickets_clean.csv",
    index=False
)

churn_events_clean.to_csv(
    r"D:\saas360\cleaned\churn_events_clean.csv",
    index=False
)

feature_usage_valid.to_csv(
    r"D:\saas360\cleaned\feature_usage_valid.csv",
    index=False
)

print("All cleaned files saved successfully!")

All cleaned files saved successfully!

In [32]:
os.listdir(r"D:\saas360\cleaned")

['accounts_clean.csv',
 'churn_events_clean.csv',
 'feature_usage_clean.csv',
 'feature_usage_valid.csv',
 'subscriptions_clean.csv',
 'support_tickets_clean.csv']